apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: httpd-frontend
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
      - name: httpd-frontend
        image: httpd:2.4-alpine
  replicas: 3
  selector:
    matchLabels:
      type: front-end 